serviceName: 'Produtividade'
resources:
  -
    type: operacional
    alias: dias-deslocamento
  -
    type: operacional
    alias: dias-trabalhados
  -
    type: financial
    alias: calibragem-colhedora
  -
    type: financial
    alias: deslocamento-limite
  -
    type: financial
    alias: hospedagem-alimentacao
  -
    type: financial
    alias: confeccao-mapas
  -
    type: financial
    alias: custo-tecnicos-produtividade

configurations:
  -
    name: 'Custo de Confecção de Mapas'
    code: 'config-custo-confeccao-mapas'
    type: 'float'
    value: 0.22
    formatter: 'money'

proportional:
  name: 'Tamanho da Área (ha)'
  code: 'prop-tamanho-area-ha'
  signal: 'ha'
  type: 'float'
  formatter: 'decimal'

inputs:
  -
    name: 'Qdade. de Trabalhadores'
    code: 'input-qdade-trabalhadores'
    type: 'integer'
    formatter: null
  -
    name: 'Qdade. de Colhedoras'
    code: 'input-qdade-colhedoras'
    type: 'integer'
    formatter: null
  -
    name: 'Qdade. de Visitas'
    code: 'input-qdade-visitas'
    type: 'integer'
    formatter: null
  -
    name: 'Horas Trabalhadas Dia'
    code: 'input-horas-trabalhadas-dia'
    type: 'float'
    formatter: 'decimal'
  -
    name: 'Distância de Deslocamento'
    code: 'input-distancia'
    type: 'float'
    formatter: 'decimal'
  -
    name: 'Horas do Técnico (dia)'
    code: 'input-horas-tecnico'
    type: 'float'
    formatter: 'decimal'
  -
    name: 'Horas do Técnico Sênior (dia)'
    code: 'input-horas-tecnico-senior'
    type: 'float'
    formatter: 'decimal'
  -
    name: 'Custo do Técnico (hora)'
    code: 'input-custo-tecnico-hora'
    type: 'float'
    formatter: 'money'
  -
    name: 'Custo do Técnico Sênior (hora)'
    code: 'input-custo-tecnico-senior-hora'
    type: 'float'
    formatter: 'money'

transitions:
  fromConfig:
    -
      from: 'config-custo-confeccao-mapas'
      resource: 'confeccao-mapas'
      to: 'input-custo-ha'

  fromInput:
    -
      from: 'input-distancia'
      resource: 'dias-deslocamento'
      to: 'input-distancia'
    -
      from: 'input-horas-trabalhadas-dia'
      resource: 'dias-deslocamento'
      to: 'input-horas-trabalhadas-dia'
    -
      from: 'input-qdade-colhedoras'
      resource: 'calibragem-colhedora'
      to: 'input-qdade-colhedoras'
    -
      from: 'input-qdade-visitas'
      resource: 'deslocamento-limite'
      to: 'input-num-visitas'
    -
      from: 'input-distancia'
      resource: 'deslocamento-limite'
      to: 'input-distancia'
    -
      from: 'input-qdade-trabalhadores'
      resource: 'hospedagem-alimentacao'
      to: 'input-qdade-trabalhadores'
    -
      from: 'input-qdade-visitas'
      resource: 'dias-trabalhados'
      to: 'input-dias-trabalhados'
    -
      from: 'input-horas-tecnico'
      resource: 'custo-tecnicos-produtividade'
      to: 'input-horas-tecnico'
    -
      from: 'input-horas-tecnico-senior'
      resource: 'custo-tecnicos-produtividade'
      to: 'input-horas-tecnico-senior'
    -
      from: 'input-custo-tecnico-hora'
      resource: 'custo-tecnicos-produtividade'
      to: 'input-custo-tecnico-hora'
    -
      from: 'input-custo-tecnico-senior-hora'
      resource: 'custo-tecnicos-produtividade'
      to: 'input-custo-tecnico-senior-hora'
    -
      from: 'input-qdade-visitas'
      resource: 'custo-tecnicos-produtividade'
      to: 'input-num-visitas'

  fromResource:
    -
      from: 'dias-deslocamento'
      resource: 'dias-trabalhados'
      to: 'input-dias-deslocamento'
    -
      from: 'dias-trabalhados'
      resource: 'hospedagem-alimentacao'
      to: 'input-dias-trabalhados'
